# Cargo [manifest](https://doc.rust-lang.org/cargo/reference/manifest.html).

[package]
name = "a-million-digits-of-pi"
version = "0.1.0"
edition = "2024"
authors = ["Balint Toth"]
rust-version = "1.98"
description = "calculate the digits of Pi with the Chudnovsky algorithm"
repository = "https://github.com/tbali0524/a-million-digits-of-pi/"
license = "MIT"
keywords = ["pi", "chudnovsky"]

[profile.profiling]
inherits = "release"
debug = true

[lib]
path = "src/lib.rs"
name = "pi_digits"

[[bin]]
path = "src/main.rs"
name = "pi_digits"

[target.'cfg(not(target_os = "windows"))'.dependencies]
rug = "1.28.1"

[target.'cfg(target_os = "windows")'.dependencies]
num-bigint = "0.5"  # rug crate does not support Windows MSVC target, num-bigint is a much slower fallback.
