# Cargo manifest file for Rust solutions.
# @see https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "a-million-digits-of-pi"
version = "0.1.0"
edition = "2021"
authors = ["Balint Toth"]
rust-version = "1.85"
description = "gets the digits of pi"
# repository = "https://github.com/tbali0524/a-million-digits-of-pi/"
license = "MIT"
keywords = ["pi", "chudnovsky"]

[profile.profiling]
inherits = "release"
debug = true

[lib]
path = "src/lib.rs"
name = "pi_digits"

[[bin]]
path = "src/main.rs"
name = "pi_digits"

[dependencies]
num-bigint = "0.4"
# rug = "1.26"  # Windows MSVC target is not supported
